### ISSUE TITLE
Implement tool for PLONK circuit generation

### ISSUE THREAD

**Issue by miloszm** [dusk-network/moat#22]
#### Summary
We would like to have an automation of circuit creation for users which are not aware of the details and intricacies of PLONK CIRCUITS, for the most popular scenarios like proving someone's age. A tool should allow users to create a high level and easy to understand schema, and to generate the relevant circuit and elements of a proof system.

#### Possible solution design or implementation
Schema could be implemented using a Rust crate named "pest", which would produce a walkable Rust structure containing the elements which could be taken as a basis for the circuit generation.

#### Additional context
It has to be determined where the implementation will take place, in Moat, Citadel, or in a new project (or divided between these parts).

**Comment by HDauven** [comment]
No longer relevant.
