### ISSUE TITLE
Document Moat binary flows (sequence diagram and prose) and how to use the Moat binary

### ISSUE THREAD

**Issue by miloszm** [dusk-network/moat#31]
#### Summary
Document the context in which Moat binary operates, including a sequence diagram and prose about the Citadel flows which touch license contract, dusk blockchain, user, LP and SP.

#### Possible solution design or implementation
Write text and draw a sequence diagram, partly based on Citadel implementation specs.

#### Additional context
This is important for the community to be able to embrace and play with the technology around Citadel and the Dusk Blockchain.

**Comment by xevisalle** [comment]
Done in the wiki.
