### ISSUE TITLE
Attach a tech Moat demo to testnet - LP and SP plus a Moat binary client

### ISSUE THREAD

**Issue by miloszm** [dusk-network/moat#33]
#### Summary
In order to allow users to start playing with Citadel and Moat, we need LP and SP servers running along a testnet. Moat binary client could be used to interact with LP and SP.

#### Possible solution design or implementation
LP and SP are servers in a blockchain sense, they could be Moat clients running as periodically checking loops.

**Comment by xevisalle** [comment]
Closing because current implementation can already be tested with the provided examples / tutorials.
